version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: .
    image: eu.gcr.io/slam-lang/slam-example-api
    environment:
      PORT: 3000
      PGHOST: db
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src

volumes:
  dbdata:
